REM ---------------------------------------------------------------------------
REM  NAME          : ECASA1335.SQL
REM  Author        : Yi Jie
REM  Creation Date : 13-12-2016
REM  Run By        : SYSTEM
REM  Description   : SQL script to create new role ECAS_DPLAB_ROLE,
REM		   : grant tables to role, CREATE NEW USER AND GRANT ROLE TO USER 					ECAS_DPLAB
REM ---------------------------------------------------------------------------

PROMPT Create ROLE ECAS_DPLAB_ROLE ....
CREATE ROLE ECAS_DPLAB_ROLE NOT IDENTIFIED;

PROMPT GRANT PRIVILEDGE TO ROLE .....
GRANT SELECT ON ECASMGR.ECAS_HDB_CP_LOT TO ECAS_DPLAB_ROLE;
GRANT SELECT ON ECASMGR.ECAS_LTA_PTE_CP_VACANT_LOT TO ECAS_DPLAB_ROLE;
GRANT SELECT ON ECASMGR.ECAS_SP_REALTIME TO ECAS_DPLAB_ROLE;
GRANT SELECT ON ECASMGR.ECAS_SP_INTERFACE TO ECAS_DPLAB_ROLE;
GRANT SELECT ON ECASMGR.ECAS_HDB_CP_LOT_ARCHIVE TO ECAS_DPLAB_ROLE;
GRANT SELECT ON ECASMGR.ECAS_LTA_PTE_CP_LOT_ARCHIVE TO ECAS_DPLAB_ROLE;


PROMT CREATE USER ECAS_DPLAB.....
CREATE USER ECAS_DPLAB 
IDENTIFIED BY "********" 
DEFAULT TABLESPACE "APPL_DATA" 
TEMPORARY TABLESPACE "TEMP" 
ACCOUNT UNLOCK;

PROMPT GRANT USER ACCESS....
GRANT "APPL_USER" TO "ECAS_DPLAB";

PROMPT GRANT ROLE TO USER.....
GRANT "ECAS_DPLAB_ROLE" TO "ECAS_DPLAB";


