CREATE TABLE  ECAS_LTA_PTE_CP_RATES_ARCHIVE (
  carpark_rate_id     VARCHAR2(15)  NOT NULL,
  carpark_id      VARCHAR2(15),
  carpark_name    VARCHAR2(100)  NOT NULL,
  category    VARCHAR2(50),
  weekday_rate1   VARCHAR2(1000),
  weekday_rate2   VARCHAR2(1000),
  saturday_rate   VARCHAR2(1000),
  sunday_PH_rate  VARCHAR2(1000),
  summary     VARCHAR2(2000),
  latitude      VARCHAR2(20),
  longitude     VARCHAR2(20),
  flag        VARCHAR2(1),
  source_cre_dt     DATE,
  upd_dt      DATE,
  cre_dt      DATE  NOT NULL
 )
  TABLESPACE APPL_DATA
  STORAGE (
    INITIAL    1024 K
    NEXT       1024 K
    MINEXTENTS    1
    MAXEXTENTS UNLIMITED
    PCTINCREASE   0
  )
/

ALTER TABLE ECAS_LTA_PTE_CP_RATES_ARCHIVE
  ADD CONSTRAINT ECAS_LTA_PTE_CP_RATES_ARCH_PK PRIMARY KEY (
    carpark_rate_id,
    cre_dt
  )
  USING INDEX
    TABLESPACE APPL_DATA
    STORAGE (
      INITIAL      64 K
      NEXT       1024 K
      MINEXTENTS    1
      MAXEXTENTS UNLIMITED
      PCTINCREASE   0
    )
/


CREATE TABLE  ECAS_LTA_PTE_CP_LOT_ARCHIVE (
  carpark_id      VARCHAR2(15)  NOT NULL,
  area        VARCHAR2(30)  NOT NULL,
  development   VARCHAR2(100),
  lots      NUMBER,
  Summary   VARCHAR2(200),
  latitude    VARCHAR2(20),
  longitude   VARCHAR2(20),
  distance    VARCHAR2(10),
  flag      VARCHAR2(1),
  source_cre_dt     DATE,
  upd_dt    DATE,
  cre_dt    DATE  NOT NULL
)
  TABLESPACE APPL_DATA
  STORAGE (
    INITIAL    1024 K
    NEXT       1024 K
    MINEXTENTS    1
    MAXEXTENTS UNLIMITED
    PCTINCREASE   0
  )
/

PROMPT ----- CREATE PRIMARY KEY FOR ecas_lta_pte_cp_vacant_lot ... 

ALTER TABLE  ECAS_LTA_PTE_CP_LOT_ARCHIVE
  ADD CONSTRAINT  ECAS_LTA_PTE_CP_LOT_ARCHIVE_PK PRIMARY KEY (
    carpark_id,
    cre_dt
  )
  USING INDEX
    TABLESPACE APPL_DATA
    STORAGE (
      INITIAL      64 K
      NEXT       1024 K
      MINEXTENTS    1
      MAXEXTENTS UNLIMITED
      PCTINCREASE   0
    )
/

PROMPT CREATING STORE TRIGGER B4UPDATE_ECAS_LTA_PTE_CP_RATES_ARCHIVE

CREATE OR REPLACE TRIGGER B4UPDATE_ECAS_LTA_PTE_CP_RATES_ARCHIVE
BEFORE UPDATE
ON ECAS_LTA_PTE_CP_RATES_ARCHIVE
FOR EACH ROW
BEGIN
   :NEW.upd_dt    := sysdate;
END;
/

SHOW ERROR;


PROMPT CREATING STORE TRIGGER B4INSERT_ECAS_LTA_PTE_CP_RATES_ARCHIVE

CREATE OR REPLACE TRIGGER B4INSERT_ECAS_LTA_PTE_CP_RATES_ARCHIVE
BEFORE INSERT
ON ECAS_LTA_PTE_CP_RATES_ARCHIVE
FOR EACH ROW
BEGIN
   :NEW.cre_dt    := sysdate;
END;
/

SHOW ERROR;

PROMPT CREATING STORE TRIGGER B4INSERT_ECAS_LTA_PTE_CP_LOT_ARCHIVE

CREATE OR REPLACE TRIGGER B4INSERT_ECAS_LTA_PTE_CP_LOT_ARCHIVE
BEFORE INSERT
ON ECAS_LTA_PTE_CP_LOT_ARCHIVE
FOR EACH ROW
BEGIN
   :NEW.cre_dt    := sysdate;
END;
/

SHOW ERROR;


PROMPT CREATING STORE TRIGGER B4UPDATE_ECAS_LTA_PTE_CP_LOT_ARCHIVE

CREATE OR REPLACE TRIGGER B4UPDATE_ECAS_LTA_PTE_CP_LOT_ARCHIVE
BEFORE UPDATE
ON ECAS_LTA_PTE_CP_LOT_ARCHIVE
FOR EACH ROW
BEGIN
   :NEW.upd_dt    := sysdate;
END;
/

SHOW ERROR;