CREATE OR REPLACE TRIGGER "AFTER_INS_ECAS_LTA_PTE_CP_RATES" 
AFTER INSERT
ON ECAS_LTA_PTE_CP_RATES
FOR EACH ROW

BEGIN
	INSERT INTO ECAS_LTA_PTE_CP_RATES_ARCHIVE (CARPARK_RATE_ID, CARPARK_ID, CARPARK_NAME, CATEGORY, WEEKDAY_RATE1, WEEKDAY_RATE2, SATURDAY_RATE, SUNDAY_PH_RATE, SUMMARY, LATITUDE, LONGITUDE, FLAG, SOURCE_CRE_DT)
	VALUES (:NEW.CARPARK_RATE_ID, :NEW.CARPARK_ID, :NEW.CARPARK_ID, :NEW.CARPARK_NAME, :NEW.CATEGORY, :NEW.WEEKDAY_RATE1,:NEW.WEEKDAY_RATE2,:NEW.SATURDAY_RATE,:NEW.SUNDAY_PH_RATE,:NEW.SUMMARY,:NEW.LATITUDE,:NEW.LONGITUDE,:NEW.FLAG,:NEW.SOURCE_CRE_DT);
END;

/

CREATE OR REPLACE TRIGGER "AFTER_INS_ECAS_LTA_PTE_CP_VACANT_LOT" 
AFTER INSERT
ON ECAS_LTA_PTE_CP_VACANT_LOT
FOR EACH ROW

BEGIN
	INSERT INTO ECAS_HDB_CP_LOT_ARCHIVE (CARPARK_ID, AREA, DEVELOPMENT, LOTS, SUMMARY, LATITUDE, LONGITUDE, DISTANCE, FLAG,SOURCE_CRE_DT)
	VALUES (:NEW.CARPARK_ID, :NEW.AREA, :NEW.DEVELOPMENT, :NEW.LOTS, :NEW.SUMMARY, :NEW.LATITUDE, :NEW.LONGITUDE, :NEW.DISTANCE, :NEW.FLAG, :NEW.SOUCE_CRE_DT);	
END;
