CREATE ROLE "ECAS_CARPARK_ROLE" NOT IDENTIFIED;
 
GRANT SELECT ON "ECASMGR"."ECAS_HDB_CP_LOT" TO "ECAS_CARPARK_ROLE";
GRANT SELECT ON "ECASMGR"."ECAS_LTA_PTE_CP_VACANT_LOT" TO "ECAS_CARPARK_ROLE";
GRANT SELECT ON "ECASMGR"."ECAS_SP_REALTIME" TO "ECAS_CARPARK_ROLE";
GRANT SELECT ON "ECASMGR"."ECAS_SP_INTERFACE" TO "ECAS_CARPARK_ROLE";
GRANT SELECT ON "ECASMGR"."ECAS_HDB_CP_LOT_ ARCHIVE" TO "ECAS_CARPARK_ROLE";
GRANT SELECT ON "ECASMGR"."ECAS_LTA_PTE_CP_LOT_ARCHIVE" TO "ECAS_CARPARK_ROLE";
 
CREATE USER "ECAS_REPLICATE" PROFILE "QUERY_USER_PROFILE" IDENTIFIED BY "XXX" DEFAULT TABLESPACE "INTERNET_TS" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "APPL_USER" TO "ECAS_REPLICATE ";
GRANT "ECAS_CARPARK_ROLE" TO "ECAS_REPLICATE ";