
  CREATE TABLE "ECASMGR"."ECAS_SP_INTERFACE" 
   (	"CARPARK_NO" VARCHAR2(10 BYTE), 
	"LOT_TYPE" VARCHAR2(12 BYTE), 
	"LOTS_AVAILABLE" VARCHAR2(10 BYTE), 
	"TOTAL_OPER_LOTS" VARCHAR2(5 BYTE), 
	"SOURCE_UPD_DATE" DATE, 
	"SOURCE_UPD_TIME" DATE, 
	"CRE_DATE" DATE, 
	"CRE_USER_ID" VARCHAR2(10 BYTE), 
	"UPD_DATE" DATE, 
	"UPD_USER_ID" VARCHAR2(10 BYTE)
   ) 
  TABLESPACE APPL_DATA
  STORAGE (
    INITIAL    1024 K
    NEXT       1024 K
    MINEXTENTS    1
    MAXEXTENTS UNLIMITED
    PCTINCREASE   0
  )


CREATE OR REPLACE TRIGGER "ECASMGR"."B4_INS_ECAS_SP_INTERFACE" 
BEFORE INSERT
ON ECAS_SP_INTERFACE
FOR EACH ROW
BEGIN
   :NEW.cre_date    := SYSDATE;
   :NEW.cre_user_id := USER;
END;

/
ALTER TRIGGER "ECASMGR"."B4_INS_ECAS_SP_INTERFACE" ENABLE;

  CREATE OR REPLACE TRIGGER "ECASMGR"."B4_UPD_ECAS_SP_INTERFACE" 
BEFORE UPDATE
ON ECAS_SP_INTERFACE
FOR EACH ROW
BEGIN
   :NEW.UPD_DATE    := SYSDATE;
   :NEW.UPD_USER_ID := USER;
END;

/
ALTER TRIGGER "ECASMGR"."B4_UPD_ECAS_SP_INTERFACE" ENABLE;

  CREATE OR REPLACE TRIGGER "ECASMGR"."AFTER_INS_ECAS_SP_INTERFACE" 
AFTER INSERT
ON ECAS_SP_INTERFACE
FOR EACH ROW

DECLARE
   CNT NUMBER (3);

BEGIN

SELECT COUNT(*) INTO CNT FROM ECAS_SP_REALTIME WHERE CARPARK_NO = :NEW.CARPARK_NO AND LOT_TYPE = :NEW.LOT_TYPE;

IF (CNT = 0) THEN
	INSERT INTO ECAS_SP_REALTIME (CARPARK_NO, LOT_TYPE, LOTS_AVAILABLE, TOTAL_OPER_LOTS)
	VALUES (:NEW.CARPARK_NO, :NEW.LOT_TYPE, :NEW.LOTS_AVAILABLE, :NEW.TOTAL_OPER_LOTS);
END IF;

IF (CNT > 0) THEN
	UPDATE ECAS_SP_REALTIME
	SET LOTS_AVAILABLE = :NEW.LOTS_AVAILABLE, TOTAL_OPER_LOTS = :NEW.TOTAL_OPER_LOTS
	WHERE CARPARK_NO = :NEW.CARPARK_NO AND 
	LOT_TYPE = :NEW.LOT_TYPE;
END IF;
	
END;
/
ALTER TRIGGER "ECASMGR"."AFTER_INS_ECAS_SP_INTERFACE" ENABLE;
