CREATE TABLE "ECAS_HDB_CP_LOT_ARCHIVE" (
	carpark_no              VARCHAR2(5) NOT NULL,
	lot_type                VARCHAR2(1) NOT NULL,
	lot_available           NUMBER(5,0) NOT NULL,
	date_time               DATE NOT NULL
)
  TABLESPACE APPL_DATA
  STORAGE (
    INITIAL    1024 K
    NEXT       1024 K
    MINEXTENTS    1
    MAXEXTENTS UNLIMITED
    PCTINCREASE   0
  )
/
ALTER TABLE "ECAS_HDB_CP_LOT_ARCHIVE"
  ADD CONSTRAINT hdb_cp_lot_pk PRIMARY KEY (
    carpark_no,
    cre_dt
  )
  USING INDEX
    TABLESPACE APPL_DATA
    STORAGE (
      INITIAL      64 K
      NEXT       1024 K
      MINEXTENTS    1
      MAXEXTENTS UNLIMITED
      PCTINCREASE   0
    )

/

CREATE OR REPLACE TRIGGER "AFTER_INS_ECAS_HDB_CP_LOT" 
AFTER INSERT
ON ECAS_HDB_CP_LOT
FOR EACH ROW

BEGIN
  INSERT INTO ECAS_HDB_CP_LOT_ARCHIVE (CARPARK_NO, LOT_TYPE, LOT_AVAILABLE)
  VALUES (:NEW.CARPARK_NO, :NEW.LOT_TYPE, :NEW.LOT_AVAILABLE);  
END;

/

CREATE OR REPLACE TRIGGER B4_INS_ECAS_HDB_CP_LOT_ARCHIVE
BEFORE INSERT
ON ECAS_HDB_CP_LOT_ARCHIVE
FOR EACH ROW
BEGIN
   :NEW.DATE_TIME    := SYSDATE;
END;

/
ALTER TRIGGER B4_INS_ECAS_HDB_CP_LOT_ARCHIVE ENABLE;

CREATE OR REPLACE TRIGGER B4_UPD_ECAS_HDB_CP_LOT_ARCHIVE
BEFORE UPDATE
ON ECAS_HDB_CP_LOT_ARCHIVE
FOR EACH ROW
BEGIN
   :NEW.DATE_TIME    := SYSDATE;
END;

/
ALTER TRIGGER B4_INS_ECAS_HDB_CP_LOT_ARCHIVE ENABLE;

/
CREATE TABLE  ECAS_LTA_PTE_CP_LOT_ARCHIVE (
  carpark_id      VARCHAR2(15)  NOT NULL,
  area        VARCHAR2(30)  NOT NULL,
  development   VARCHAR2(100),
  lots      NUMBER,
  Summary   VARCHAR2(200),
  latitude    VARCHAR2(20),
  longitude   VARCHAR2(20),
  distance    VARCHAR2(10),
  flag      VARCHAR2(1),
  source_cre_dt     DATE,
  upd_dt    DATE,
  cre_dt    DATE  NOT NULL
)
  TABLESPACE APPL_DATA
  STORAGE (
    INITIAL    1024 K
    NEXT       1024 K
    MINEXTENTS    1
    MAXEXTENTS UNLIMITED
    PCTINCREASE   0
  )
/

ALTER TABLE  ECAS_LTA_PTE_CP_LOT_ARCHIVE
  ADD CONSTRAINT  ECAS_LTA_PTE_CP_LOT_ARCHIVE_PK PRIMARY KEY (
    carpark_id,
    cre_dt
  )
  USING INDEX
    TABLESPACE APPL_DATA
    STORAGE (
      INITIAL      64 K
      NEXT       1024 K
      MINEXTENTS    1
      MAXEXTENTS UNLIMITED
      PCTINCREASE   0
    )
/

CREATE OR REPLACE TRIGGER "AFTER_INS_ECAS_LTA_PTE_CP_VACA" 
AFTER INSERT
ON ECAS_LTA_PTE_CP_VACANT_LOT
FOR EACH ROW

BEGIN
  INSERT INTO ECAS_LTA_PTE_CP_LOT_ARCHIVE (CARPARK_ID, AREA, DEVELOPMENT, LOTS, SUMMARY, LATITUDE, LONGITUDE, DISTANCE, FLAG,SOURCE_CRE_DT)
  VALUES (:NEW.CARPARK_ID, :NEW.AREA, :NEW.DEVELOPMENT, :NEW.LOTS, :NEW.SUMMARY, :NEW.LATITUDE, :NEW.LONGITUDE, :NEW.DISTANCE, :NEW.FLAG, :NEW.SOURCE_CRE_DT);  
END;

/

CREATE OR REPLACE TRIGGER B4INSERT_ECAS_LTA_PTE_CP_LOT_ARCHIVE
BEFORE INSERT
ON ECAS_LTA_PTE_CP_LOT_ARCHIVE
FOR EACH ROW
BEGIN
   :NEW.cre_dt    := sysdate;
END;
/


CREATE OR REPLACE TRIGGER B4UPDATE_ECAS_LTA_PTE_CP_LOT_ARCHIVE
BEFORE UPDATE
ON ECAS_LTA_PTE_CP_LOT_ARCHIVE
FOR EACH ROW
BEGIN
   :NEW.upd_dt    := sysdate;
END;